apiVersion: v1
kind: ConfigMap
metadata:
  name: clustershift-benchmark-config
  namespace: benchmark
data:
  DB_HOST: "http://192.168.133.10"
  DB_PORT: "8080"
  DB_USER: "user"
  DB_PASSWORD: "password"
  DB_NAME: "name"
  DB_TYPE: "postgres" # or "mongodb"
  MONGODB_URI: "mongodb://user:password@localhost:27017/dbname"
